In [27]:
from PIL import Image
import numpy as np


In [28]:
im = np.array(Image.open('../../imgs/lena_gray_512_e9d6b69ae2ff469cf0da5882b91dbc4f.tif'))
print(im.shape)

(512, 512)


In [29]:
print(im[0,0])
print(im[0:2, :].shape)

# barra preta na parte de cima
#im[200:210, :] = 0


162
(2, 512)


In [30]:
#quadrado preto de 20x20 em cada canto da imagem

im[ 0:20, 0:20 ] = 0
im[ 0:20, -20: ] = 0
im[ -20:, 0:20 ] = 0
im[ -20:, -20: ] = 0

In [31]:
print(im)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [32]:
im_pil = Image.fromarray(im)
im_pil.save('example1.png')